// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmMediaWorkManagement.ApiService.DataContext;

#nullable disable

namespace OmMediaWorkManagement.ApiService.Migrations
{
    [DbContext(typeof(OmContext))]
    [Migration("20241204120746_replaceddeciamla")]
    partial class replaceddeciamla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.JobImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JobTodoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobTodoId");

                    b.ToTable("JobImages");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.JobToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("DueBalance")
                        .HasColumnType("int");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JobPostedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("JobStatusType")
                        .HasColumnType("int");

                    b.Property<int>("OmClientId")
                        .HasColumnType("int");

                    b.Property<int>("OmEmpId")
                        .HasColumnType("int");

                    b.Property<int?>("PaidAmount")
                        .HasColumnType("int");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double");

                    b.Property<int?>("TotalPayable")
                        .HasColumnType("int");

                    b.Property<int?>("total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OmClientId");

                    b.HasIndex("OmEmpId");

                    b.ToTable("JobToDo");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.JobTypeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JobStatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JobStatusType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobTypeStatus");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OmClient");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmClientWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DueBalance")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPushSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSMSSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OmClientId")
                        .HasColumnType("int");

                    b.Property<int?>("PaidAmount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PrintCount")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.Property<int?>("TotalPayable")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkDetails")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OmClientId");

                    b.HasIndex("UserId");

                    b.ToTable("OmClientWork");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AppPin")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeProfilePath")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSalaryPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OTP")
                        .HasColumnType("longtext");

                    b.Property<int>("OTPAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OTPExpireTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("OTPGeneratedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SalaryAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OmEmployee");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmEmployeeDocuments", b =>
                {
                    b.Property<int>("OmEmployeeDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OmEmployeeDocumentId"));

                    b.Property<string>("EmployeeDocumentsPath")
                        .HasColumnType("longtext");

                    b.Property<int>("OmEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("OmEmployeeDocumentId");

                    b.HasIndex("OmEmployeeId");

                    b.ToTable("OmEmployeeDocuments");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmEmployeeSalaryManagement", b =>
                {
                    b.Property<int>("EmployeeSalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeSalaryId"));

                    b.Property<decimal?>("AdvancePayment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("AdvancePaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DueBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OmEmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("OverBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OverTimeSalary")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("EmployeeSalaryId");

                    b.HasIndex("OmEmployeeId");

                    b.ToTable("OmEmployeeSalaryManagement");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmEmployeeShift", b =>
                {
                    b.Property<int>("EmployeeShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeShiftId"));

                    b.Property<int>("OmEmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("OverTimePerHourCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ShiftOverTime")
                        .HasColumnType("longtext");

                    b.Property<string>("ShiftTiming")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EmployeeShiftId");

                    b.HasIndex("OmEmployeeId");

                    b.ToTable("OmEmployeeShift");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmMachines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MachineDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("MachineName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OmMachines");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.UserRegistration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OTP")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OTPExpireTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.UserRegistration", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.UserRegistration", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmMediaWorkManagement.ApiService.Models.UserRegistration", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.UserRegistration", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.JobImages", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.JobToDo", "JobToDo")
                        .WithMany("JobImages")
                        .HasForeignKey("JobTodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobToDo");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.JobToDo", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.OmClient", "OmClient")
                        .WithMany("JobToDo")
                        .HasForeignKey("OmClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmMediaWorkManagement.ApiService.Models.OmEmployee", "OmEmployee")
                        .WithMany()
                        .HasForeignKey("OmEmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OmClient");

                    b.Navigation("OmEmployee");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmClient", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.UserRegistration", "UserRegistration")
                        .WithMany("OmClient")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRegistration");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmClientWork", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.OmClient", "OmClient")
                        .WithMany("OmClientWork")
                        .HasForeignKey("OmClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmMediaWorkManagement.ApiService.Models.UserRegistration", "UserRegistration")
                        .WithMany("OmClientWork")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OmClient");

                    b.Navigation("UserRegistration");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmEmployee", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.UserRegistration", "UserRegistration")
                        .WithMany("OmEmployee")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRegistration");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmEmployeeDocuments", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.OmEmployee", "OmEmployee")
                        .WithMany("EmployeeDocuments")
                        .HasForeignKey("OmEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OmEmployee");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmEmployeeSalaryManagement", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.OmEmployee", "OmEmployee")
                        .WithMany()
                        .HasForeignKey("OmEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OmEmployee");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmEmployeeShift", b =>
                {
                    b.HasOne("OmMediaWorkManagement.ApiService.Models.OmEmployee", "OmEmployee")
                        .WithMany()
                        .HasForeignKey("OmEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OmEmployee");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.JobToDo", b =>
                {
                    b.Navigation("JobImages");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmClient", b =>
                {
                    b.Navigation("JobToDo");

                    b.Navigation("OmClientWork");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.OmEmployee", b =>
                {
                    b.Navigation("EmployeeDocuments");
                });

            modelBuilder.Entity("OmMediaWorkManagement.ApiService.Models.UserRegistration", b =>
                {
                    b.Navigation("OmClient");

                    b.Navigation("OmClientWork");

                    b.Navigation("OmEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
